mybatis:
  config-locations: classpath:mapping/confg.xml
  mapper-locations: classpath:mapping/mapper/*.xml
  type-aliases-package: com.jk.model
server:
  port: 8083
spring:
  data:
    solr:
      host: http://127.0.0.1:8080/solr
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 1011
    url: jdbc:mysql://localhost:3306/shixun?useUnicode=true&characterEncoding=utf-8
    username: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html